name: Build and Release Game

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GODOT_VERSION: 4.4
  EXPORT_NAME: demo_game


jobs:
  build:
    name: Build Game
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.4

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Export Directory
        run: |
          mkdir -v -p build/windows ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Game (Windows)
        run: godot --headless -v --export-release "Windows Desktop" ./build/windows/${EXPORT_NAME}.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./build/windows/
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: ./build/windows/
