name: Build and Release Game

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.4
  EXPORT_NAME: demo_game


jobs:
  build:
    name: Build Game
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.4

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Export Directory
        run: |
          mkdir -v -p build/windows ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Game (Windows)
        run: godot -v --export-release "Windows Desktop" ./build/windows/${EXPORT_NAME}.exe
          

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: GameBuild
          path: build/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
